server:
  port: 8081

integrations:
  clients:
    products-client:
      url: http://localhost:8080
      connect-timeout: 5s
      read-timeout: 10s

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dz4
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true