DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS product_categories;

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS product_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) UNIQUE
);

CREATE TABLE IF NOT EXISTS products
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number            BIGINT NOT NULL UNIQUE,
    balance                   BIGINT,
    product_category_id       BIGINT REFERENCES product_categories (id) ON DELETE CASCADE,
    user_id                   BIGINT REFERENCES users (id) ON DELETE CASCADE

);

insert into product_categories values (1, 'CARD');
insert into product_categories values (2, 'ACCOUNT')

